-- DDL SISTEMA NOVO PROTOCOLO

-- USUARIO

CREATE TABLE USRDBVAH.TB_GESCON_USUARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  DS_LOGIN VARCHAR2(30) NOT NULL UNIQUE,
  NM_TITULO VARCHAR2(75),
  NM_EMAIL VARCHAR2(75),
  CD_ROLE VARCHAR2(15) NOT NULL
);

CREATE SEQUENCE USRDBVAH.SEQ_GESCON_USUARIO;

-- GERENCIAS DO USUARIO

CREATE TABLE USRDBVAH.TB_GESCON_GER_USUARIO
(
  ID_USUARIO NUMBER(*) NOT NULL,
  CD_GERENCIA VARCHAR2(20) NOT NULL,
  CONSTRAINT TB_GESCON_GER_USUARIO_PK PRIMARY KEY (ID_USUARIO, CD_GERENCIA),
  CONSTRAINT TB_GESCON_GER_USUARIO_FK1 FOREIGN KEY (ID_USUARIO) REFERENCES USRDBVAH.TB_GESCON_USUARIO (ID)
);

-- CONTRATO

CREATE TABLE USRDBVAH.TB_GESCON_CONTRATO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  NM_FORNECEDOR VARCHAR2(150) NOT NULL,
  SN_RENOVAR VARCHAR2(1),
  CD_TIPO VARCHAR2(20) NOT NULL,
  CD_GERENCIA VARCHAR2(20),
  CD_STATUS VARCHAR2(10) NOT NULL,
  NM_EMAIL1 VARCHAR2(75),
  NM_EMAIL2 VARCHAR2(75),
  NM_LOCALIZACAO VARCHAR2(100),
  NM_VIGENCIA VARCHAR2(30),
  DT_INICIO DATE,
  DT_TERMINO DATE,
  DT_VENC_ANEXO DATE
);

CREATE SEQUENCE USRDBVAH.SEQ_GESCON_CONTRATO;

-- ARQUIVO

CREATE TABLE USRDBVAH.TB_GESCON_ARQUIVO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_CONTRATO NUMBER(*) NOT NULL,
  NM_NOME VARCHAR2(30) NOT NULL,
  VL_CONTEUDO BLOB NOT NULL,
  CONSTRAINT TB_GESCON_ARQUIVO_FK1 FOREIGN KEY (ID_CONTRATO) REFERENCES USRDBVAH.TB_GESCON_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_GESCON_ARQUIVO;

-- DIAS AVISO

CREATE TABLE USRDBVAH.TB_GESCON_DIAS_AVISO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  VL_DIAS INTEGER NOT NULL,
  SN_AVISO_DIARIO VARCHAR2(1) DEFAULT '0'
);

CREATE SEQUENCE USRDBVAH.SEQ_GESCON_DIAS_AVISO;

-- DROPS

DROP TABLE USRDBVAH.TB_GESCON_ARQUIVO;
DROP TABLE USRDBVAH.TB_GESCON_CONTRATO;
DROP TABLE USRDBVAH.TB_GESCON_DIAS_AVISO;
DROP TABLE USRDBVAH.TB_GESCON_GER_USUARIO;
DROP TABLE USRDBVAH.TB_GESCON_USUARIO;
DROP SEQUENCE USRDBVAH.SEQ_GESCON_ARQUIVO;
DROP SEQUENCE USRDBVAH.SEQ_GESCON_CONTRATO;
DROP SEQUENCE USRDBVAH.SEQ_GESCON_USUARIO;
DROP SEQUENCE USRDBVAH.SEQ_GESCON_DIAS_AVISO;
