-- DDL SISTEMA SISPAG

-- USUARIO

CREATE TABLE USRDBVAH.TB_SISPAG_USUARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  DS_LOGIN VARCHAR2(30) NOT NULL UNIQUE,
  NM_TITULO VARCHAR2(75),
  NM_EMAIL VARCHAR2(75),
  CD_ROLE VARCHAR2(15) NOT NULL
);

CREATE SEQUENCE USRDBVAH.SEQ_SISPAG_USUARIO;

-- GUIA

CREATE TABLE USRDBVAH.TB_SISPAG_GUIA
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  CD_TIPO NUMBER(1) NOT NULL,
  CD_CONVENIO NUMBER(*) NOT NULL,
  DT_EMISSAO DATE NOT NULL,
  CD_PRESTADOR NUMBER(*),
  CD_GUIA VARCHAR2(20),
  CD_SOLICITACAO VARCHAR2(20),
  CD_SENHA VARCHAR2(20),
  CD_CARTAO VARCHAR2(20),
  CD_CNES VARCHAR2(15),
  NM_PACIENTE VARCHAR2(100),
  CONSTRAINT TB_SISPAG_GUIA_FK1 FOREIGN KEY (CD_CONVENIO) REFERENCES DBAMV.CONVENIO (CD_CONVENIO),
  CONSTRAINT TB_SISPAG_GUIA_FK2 FOREIGN KEY (CD_PRESTADOR) REFERENCES DBAMV.PRESTADOR (CD_PRESTADOR)
);

CREATE SEQUENCE USRDBVAH.SEQ_SISPAG_GUIA;

-- ITEM GUIA

CREATE TABLE USRDBVAH.TB_SISPAG_IT_GUIA
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_GUIA NUMBER(*) NOT NULL,
  NM_NOME VARCHAR2(150),
  CONSTRAINT TB_SISPAG_IT_GUIA_FK1 FOREIGN KEY (ID_GUIA) REFERENCES USRDBVAH.TB_SISPAG_GUIA (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_SISPAG_IT_GUIA;

-- EVENTO

CREATE TABLE USRDBVAH.TB_SISPAG_EVENTO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_GUIA NUMBER(*) NOT NULL,
  CD_TIPO NUMBER(1) NOT NULL,
  ID_USUARIO NUMBER(*) NOT NULL,
  DT_EVENTO DATE NOT NULL,
  NM_MENSAGEM VARCHAR2(150),
  CONSTRAINT TB_SISPAG_EVENTO_FK1 FOREIGN KEY (ID_GUIA) REFERENCES USRDBVAH.TB_SISPAG_GUIA (ID),
  CONSTRAINT TB_SISPAG_EVENTO_FK2 FOREIGN KEY (ID_USUARIO) REFERENCES USRDBVAH.TB_SISPAG_USUARIO (ID)
);

CREATE SEQUENCE USRDBVAH.SEQ_SISPAG_EVENTO;

-- DROPS

DROP TABLE USRDBVAH.TB_SISPAG_EVENTO;
DROP TABLE USRDBVAH.TB_SISPAG_IT_GUIA;
DROP TABLE USRDBVAH.TB_SISPAG_GUIA;
DROP TABLE USRDBVAH.TB_SISPAG_USUARIO;
DROP SEQUENCE USRDBVAH.SEQ_SISPAG_EVENTO;
DROP SEQUENCE USRDBVAH.SEQ_SISPAG_IT_GUIA;
DROP SEQUENCE USRDBVAH.SEQ_SISPAG_GUIA;
DROP SEQUENCE USRDBVAH.SEQ_SISPAG_USUARIO;
